version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kontakas-dev"
s3_bucket = "kontakas-dev-deployment-artifacts"
s3_prefix = "kontakas-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev EnableRecaptcha=false LogLevel=debug"

[default.local_start_api]
[default.local_start_api.parameters]
parameter_overrides = "Environment=dev EnableRecaptcha=false LogLevel=debug"
