AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: > 
  Kontakas Public Demo - Serverless Application Model (SAM) template.
  This template deploys a serverless contact form API using AWS Lambda and API Gateway.

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  EnableRecaptcha:
    Type: String
    Default: "false"
    Description: Enable reCAPTCHA validation
  LogLevel:
    Type: String
    Default: "debug"
    Description: Log level for the application
  
Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs20.x
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        ENVIRONMENT: !Ref Environment
        ENABLE_RECAPTCHA: !Ref EnableRecaptcha
        LOG_LEVEL: !Ref LogLevel
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Requested-With'"
      AllowOrigin: "'*'"
      
Resources:
  SendContactUsForm:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/send-contactus-form/index.handler
      CodeUri: ./dist
      Events:
        SendContactUsFormEndpoint:
          Type: Api
          Properties:
            Path: /send-form
            Method: post

Outputs:
  SendContactUsFormApi:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SendContactUsFormFunction:
    Description: "Send contact us form Lambda Function ARN"
    Value: !GetAtt SendContactUsForm.Arn